title: Koodio Power Tools
author: Kood.io
email: support@kood.io
description: >-
  Koodio is the best and most efficient tool for creating professional and beautiful Google slides
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kood.io" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

